apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongoSecret.name }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.mongoSecret.userKey }}: {{ .Values.mongoSecret.user | default "pricelist" | quote }}
  {{ .Values.mongoSecret.passKey }}: {{ .Values.mongoSecret.pass | default "" | quote }}
